// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzCQP3jtHZGDOHCKR0gPfgWA60VpAJC2k',
    appId: '1:548922569982:android:46a2e503b532dd070721af',
    messagingSenderId: '548922569982',
    projectId: 'didi-11290',
    storageBucket: 'didi-11290.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXh8CjFdN2tWwijOs2HLywvYfKcvM1xho',
    appId: '1:548922569982:ios:71c1a574c19a14ce0721af',
    messagingSenderId: '548922569982',
    projectId: 'didi-11290',
    storageBucket: 'didi-11290.appspot.com',
    androidClientId: '548922569982-bqvmcqfuq5pde8et6vpjk1kupcb02ong.apps.googleusercontent.com',
    iosClientId: '548922569982-60rv8eh6f9tngik8u0v9f69r8qgb5k8s.apps.googleusercontent.com',
    iosBundleId: 'com.example.aithinkism',
  );
}
